export {default as Login} from './login/Login';
export {default as Admin} from './admin';
export {default as UserAdd} from './userAdd';
export {default as ThematicAdd} from './thematicAdd'
export {default as ExAdd} from './exAdd';
export {default as FileAdd} from './fileAdd';
export {default as ThemEdit} from './themEdit';
export {default as ExEdit} from './exEdit';
export {default as FileEdit} from './fileEdit';
export {default as ExView} from './exView';
export {default as Profile} from './Profile';
export {default as ExOfThem} from './exofThem';
export {default as Statatics} from './statatics';