export {default as Login} from './login/Login';
export {default as Admin} from './admin';
export {default as UserAdd} from './users/userAdd';
export {default as ThematicAdd} from './thematics/thematicAdd'
export {default as ExAdd} from './ex/exAdd';
export {default as FileAdd} from './files/fileAdd';
export {default as ThemEdit} from './thematics/themEdit';
export {default as ExEdit} from './ex/exEdit';
export {default as FileEdit} from './files/fileEdit';
export {default as ExView} from './ex/exView';
export {default as Profile} from './users/Profile';
export {default as ExOfThem} from './ex/exofThem';
export {default as Statatics} from './statatics';
export {default as CourseAdd} from './courses/courseAdd';
export {default as CourseEdit} from './courses/courseEdit';
export {default as TestAdd} from './tests/testAdd';
export {default as QuestionsList} from  './tests/questionsList';
export {default as TestEdit} from './tests/testEdit';
