export {default as Home} from './home/Home';
export {default as Profile} from './profile/Profile';
export {default as Item} from './item/Item';
export {default as Create} from './create/Create';
export {default as Login} from './login/Login';
export {default as Register} from './register/Register';
export {default as User} from './user/User';
export {default as Thematics} from './thematics/Thematics';
export {default as Exercises} from './exercises/exercises';